# 전처리

In [1]:
from google.colab import drive
drive.mount('/content/drive')
import os
os.chdir("/content/drive/MyDrive/Colab Notebooks")

Mounted at /content/drive

# 2022-06-13

In [2]:
import numpy as np
v1 = np.array([1, 2, 3, 4])
print(v1)

[1 2 3 4]

In [3]:
v1 = np.arange(10)**2
print(v1)

[ 0  1  4  9 16 25 36 49 64 81]

In [4]:
v1 = np.arange(12)
v2 = v1.reshape(2, 3, 2, order='F')
print(v2)

[[[ 0  6]
  [ 2  8]
  [ 4 10]]

 [[ 1  7]
  [ 3  9]
  [ 5 11]]]

In [5]:
v3 = np.arange(3.5, 10.5, 2, dtype=float)
print(v3)
v4 = np.arange(1, 5).reshape(2, 2)
print(v4)
print(np.amax(v3))
print(v4.shape)

[3.5 5.5 7.5 9.5]
[[1 2]
 [3 4]]
9.5
(2, 2)

# 2022-06-14

In [6]:
import pandas as pd

a = pd.Series([1, 3, 5, 7])
print(a)
print(a.values)
print(a.index)

a2 = pd.Series([1, 3, 5, 7], index = ["a", "b", "c", "d"])
print(a2)

0    1
1    3
2    5
3    7
dtype: int64
[1 3 5 7]
RangeIndex(start=0, stop=4, step=1)
a    1
b    3
c    5
d    7
dtype: int64

In [7]:
df = pd.read_csv("EX_GrapeData.csv")
df.head(6)

   continent  brand  size  period price
0          2      2  10.7   47.65   144
1          2      3  14.0   63.13   215
2          2      2   9.0   58.76   105
3          1      1   8.0   34.88    69
4          2      2  10.0   55.53   134
5          2      2  10.5   43.14   129

In [8]:
df[["price", "size"]]
df.loc[:, "size" : "price"]
df.iloc[1:7, 0:3]
df.at[5, "price"]

df = pd.read_csv("EX_GrapeData.csv")
df.rename(columns = {"period" : "time"}, inplace = True)
df["growth"] = df["size"] / df["time"]
df.head()
del df["growth"]
df

    continent  brand  size   time price
0           2      2  10.7  47.65   144
1           2      3  14.0  63.13   215
2           2      2   9.0  58.76   105
3           1      1   8.0  34.88    69
4           2      2  10.0  55.53   134
..        ...    ...   ...    ...   ...
58          1      1   5.0  16.66  21.5
59          2      1  21.0  43.00
60          2      2   5.0  12.00
61          2      3  13.0  20.00
62          2      3  31.0  19.00

[63 rows x 5 columns]

In [9]:
df = pd.read_csv("EX_GrapeData.csv")

df_continent_brand = df[(df["continent"] == 1) | (df["brand"] == 1)]
df_continent_brand.head()

df_over_size_period = df[(df["size"] >= 10) & (df["period"] >= 30)]
df_over_size_period.head()

   continent  brand  size  period price
0          2      2  10.7   47.65   144
1          2      3  14.0   63.13   215
4          2      2  10.0   55.53   134
5          2      2  10.5   43.14   129
6          2      2  16.0   54.86   155

# 2022-06-17

In [15]:
df["brand"].value_counts()
df_recode1 = df.replace({"brand": {1: 1, 2: 1, 3: 2}})
df_recode1["brand"].value_counts()

def brand_groups(series):
    if series == 1:
        return 1
    elif series == 2:
        return 1
    else:
        return 2

df["new_brand"] = df["brand"].apply(brand_groups)
df.head()

   continent  brand  size  period price  new_brand
0          2      2  10.7   47.65   144          1
1          2      3  14.0   63.13   215          2
2          2      2   9.0   58.76   105          1
3          1      1   8.0   34.88    69          1
4          2      2  10.0   55.53   134          1

In [20]:
import pandas as pd
df = pd.read_csv("EX_GrapeData.csv")
df.head()

df_num = df.to_numpy()
df_num

df2 = pd.DataFrame(df_num, columns = ["continent", "brand", "size", "period", "price"])
df2

   continent brand  size period price
0          2     2  10.7  47.65   144
1          2     3  14.0  63.13   215
2          2     2   9.0  58.76   105
3          1     1   8.0  34.88    69
4          2     2  10.0  55.53   134
..       ...   ...   ...    ...   ...
58         1     1   5.0  16.66  21.5
59         2     1  21.0   43.0
60         2     2   5.0   12.0
61         2     3  13.0   20.0
62         2     3  31.0   19.0

[63 rows x 5 columns]